
//lOGGING IN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// Saving Role Values
export const SAVE_ROLE_START = "SAVE_ROLE_START";
export const SAVE_ROLE_SUCCESS = "SAVE_ROLE_SUCCESS";
export const SAVE_ROLE_ERROR = "SAVE_ROLE_ERROR";

//show message

export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const SHOW_MESSAGE = "SHOW_MESSAGE";


//Get All roles
export const GET_ALL_ROLE_START = "GET_ALL_ROLE_START";
export const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
export const GET_ALL_ROLE_ERROR = "GET_ALL_ROLE_ERROR";

//Deleting Role Records

export const DELETE_ROLE_START = "DELETE_ROLE_START";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_ERROR = "DELETE_ROLE_ERROR";

//Get Users List

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";


//Delete USers
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";


//Getting schemes
export const GET_SCHEME_START = "GET_SCHEME_START";
export const GET_SCHEME_SUCCESS = "GET_SCHEME_SUCCESS";
export const GET_SCHEME_ERROR = "GET_SCHEME_ERROR";

// Creating Department
export const CREATE_DEPT_START = "CREATE_DEPT_START";
export const CREATE_DEPT_SUCCESS = "CREATE_DEPT_SUCCESS";
export const CREATE_DEPT_ERROR = "CREATE_DEPT_ERROR";

//fetching Dept data  

export const GET_ALL_DEPT_START = "GET_ALL_DEPT_START";
export const GET_ALL_DEPT_SUCCESS = "GET_ALL_DEPT_SUCCESS";
export const GET_ALL_DEPT_ERROR = "GET_ALL_DEPT_ERROR";

//Deleting dept

export const DELETE_DEPT_START = "DELETE_DEPT_START";
export const DELETE_DEPT_SUCCESS = "DELETE_DEPT_SUCCESS";
export const DELETE_DEPT_ERROR = "DELETE_DEPT_ERROR";

//Get All banks

export const GET_ALL_BANK_START = "GET_ALL_BANK_START";

export const GET_ALL_BANK_SUCCESS = "GET_ALL_BANK_SUCCESS";

export const GET_ALL_BANK_ERROR = "GET_ALL_BANK_ERROR";




// Saving Bank Values

export const SAVE_BANK_START = "SAVE_BANK_START";

export const SAVE_BANK_SUCCESS = "SAVE_BANK_SUCCESS";

export const SAVE_BANK_ERROR = "SAVE_BANK_ERROR";




// Updating Bank Values

export const UPDATE_BANK_START = "UPDATE_BANK_START";

export const UPDATE_BANK_SUCCESS = "UPDATE_BANK_SUCCESS";

export const UPDATE_BANK_ERROR = "UPDATE_BANK_ERROR";




//Deleting Bank Records

export const DELETE_BANK_START = "DELETE_BANK_START";
export const DELETE_BANK_SUCCESS = "DELETE_BANK_SUCCESS";
export const DELETE_BANK_ERROR = "DELETE_BANK_ERROR";

//GEt all designation

export const GET_ALL_DESIGNATION_START = "GET_ALL_DESIGNATION_START";
export const GET_ALL_DESIGNATION_SUCCESS = "GET_ALL_DESIGNATION_SUCCESS";
export const GET_ALL_DESIGNATION_ERROR = "GET_ALL_DESIGNATION_ERROR";

// Saving Designation Values

export const SAVE_DESIGNATION_START = "SAVE_DESIGNATION_START";
export const SAVE_DESIGNATION_SUCCESS = "SAVE_DESIGNATION_SUCCESS";
export const SAVE_DESIGNATION_ERROR = "SAVE_DESIGNATION_ERROR";


//Deleting Designation Records

export const DELETE_DESIGNATION_START = "DELETE_DESIGNATION_START";
export const DELETE_DESIGNATION_SUCCESS = "DELETE_DESIGNATION_SUCCESS";
export const DELETE_DESIGNATION_ERROR = "DELETE_DESIGNATION_ERROR";

//Creating User

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

//USer Role map
export const USER_ROLEMAP_START = "USER_ROLEMAP_START";
export const USER_ROLEMAP_SUCCESS = "USER_ROLEMAP_SUCCESS";
export const USER_ROLEMAP_ERROR = "USER_ROLEMAP_ERROR";

//Saving userRoleMap
export const SAVE_USER_ROLEMAP_START = "SAVE_USER_ROLEMAP_START";
export const SAVE_USER_ROLEMAP_SUCCESS = "SAVE_USER_ROLEMAP_SUCCESS";
export const SAVE_USER_ROLEMAP_ERROR = "SAVE_USER_ROLEMAP_ERROR";


//Get Role by id
export const ROLE_BY_USERID_START = "ROLE_BY_USERID_START";
export const ROLE_BY_USERID_SUCCESS = "ROLE_BY_USERID_SUCCESS";
export const ROLE_BY_USERID_ERROR = "ROLE_BY_USERID_ERROR";

//Get role menu right map
export const GET_ROLEMENU_RIGHT_MAP_START = "GET_ROLEMENU_RIGHT_MAP_START";
export const GET_ROLEMENU_RIGHT_MAP_SUCCESS = "GET_ROLEMENU_RIGHT_MAP_SUCCESS";
export const GET_ROLEMENU_RIGHT_MAP_ERROR = "GET_ROLEMENU_RIGHT_MAP_ERROR";

//Deleting user role mapping

export const DELETE_USER_ROLE_START = "DELETE_USER_ROLE_START";
export const DELETE_USER_ROLE_SUCCESS = "DELETE_USER_ROLE_SUCCESS";
export const DELETE_USER_ROLE_ERROR = "DELETE_USER_ROLE_ERROR";

//Saving user role map

export const SAVE_ROLEMENU_RIGHT_MAP_START = "SAVE_ROLEMENU_RIGHT_MAP_START";
export const SAVE_ROLEMENU_RIGHT_MAP_SUCCESS = "SAVE_ROLEMENU_RIGHT_MAP_SUCCESS";
export const SAVE_ROLEMENU_RIGHT_MAP_ERROR = "SAVE_ROLEMENU_RIGHT_MAP_ERROR";

//Get All bank name dropdown
export const GET_ALL_BANK_DROPDOWN_START = "GET_ALL_BANK_DROPDOWN_START";
export const GET_ALL_BANK_DROPDOWN_SUCCESS = "GET_ALL_BANK_DROPDOWN_SUCCESS";
export const GET_ALL_BANK_DROPDOWN_ERROR = "GET_ALL_BANK_DROPDOWN_ERROR";

//Get All branchs
export const GET_ALL_BRANCH_START = "GET_ALL_BRANCH_START";
export const GET_ALL_BRANCH_SUCCESS = "GET_ALL_BRANCH_SUCCESS";
export const GET_ALL_BRANCH_ERROR = "GET_ALL_BRANCH_ERROR";

// Saving Branch Values
export const SAVE_BRANCH_START = "SAVE_BRANCH_START";
export const SAVE_BRANCH_SUCCESS = "SAVE_BRANCH_SUCCESS";
export const SAVE_BRANCH_ERROR = "SAVE_BRANCH_ERROR";

// Updating Branch Values
export const UPDATE_BRANCH_START = "UPDATE_BRANCH_START";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_ERROR = "UPDATE_BRANCH_ERROR";

//Deleting Branch Records


export const DELETE_BRANCH_START = "DELETE_BRANCH_START";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_ERROR = "DELETE_BRANCH_ERROR";

